#!/usr/bin/env python
from configobj import ConfigObj
import argparse
import sys


# Setting argparse
parser = argparse.ArgumentParser()

parser.add_argument('first_file', type=str, help='First file')
parser.add_argument('second_file', type=str, help='second file')
parser.add_argument('result_file', type=str, help='result file')

# Parsing args
args = parser.parse_args()

source = dict(ConfigObj(args.first_file))
dest = dict(ConfigObj(args.second_file))
result = ConfigObj(args.result_file)

def dict_diff_deep(dict1, dict2, result):
    diffkeys_1 = [k for k in dict2 if ((k in dict1 and dict1[k] != dict2[k]) or (k not in dict1)) and not isinstance(dict2[k], dict)]
    for k in diffkeys_1:
        result[k] = dict2[k]
    for k in dict2:
        if isinstance(dict2[k], dict):
            if not k in dict1:
                result[k] = dict2[k]
            else:
                z =  {}
                dict_diff_deep(dict1[k], dict2[k], z)
                if z:
                    result[k] = z
    return result

#from pprint import pprint
dict_diff_deep(source, dest, result)

# Writing result
result.write()
