#!/usr/bin/env python
from configobj import ConfigObj
import argparse
import sys
import re

# Setting argparse
parser = argparse.ArgumentParser()

parser.add_argument('first_file', type=str, help='First file')
parser.add_argument('second_file', type=str, help='second file')
parser.add_argument('result_file', type=str, nargs='?', help='result file')

class stringBuf:
    s = ''
    def __init__(self, path="", mode=""):
        pass
    def read(self):
        return self.s
    def write(self, p):
        self.s += p
    def __str__(self):
        return self.s
        

# Parsing args
args = parser.parse_args()

try:
    source_buf = stringBuf()
    source_buf.s = open(args.first_file, 'r').readlines()
    source_buf.s = '\n'.join([re.sub('^;', '#', x) for x in source_buf.s])
    
    source = dict(ConfigObj(infile=source_buf, interpolation=False))
except Exception, e:
    print source_buf.s
    print 'Error while reading ' + args.first_file
    print str(e)

try:
    source_buf = stringBuf()
    source_buf.s = open(args.second_file, 'r').readlines()
    source_buf.s = '\n'.join([re.sub('^;', '#', x) for x in source_buf.s])

    dest = dict(ConfigObj(infile=source_buf, interpolation=False))
except Exception, e:
    print 'Error while reading ' + args.second_file
    print str(e)

if args.result_file:
    result = ConfigObj(args.result_file)
else:
    result = ConfigObj()

def dict_diff_deep(dict1, dict2, result):
    diffkeys_1 = [k for k in dict2 if ((k in dict1 and dict1[k] != dict2[k]) or (k not in dict1)) and not isinstance(dict2[k], dict)]
    for k in diffkeys_1:
        result[k] = dict2[k]
    for k in dict2:
        if isinstance(dict2[k], dict):
            if not k in dict1:
                result[k] = dict2[k]
            else:
                z =  {}
                dict_diff_deep(dict1[k], dict2[k], z)
                if z:
                    result[k] = z
    return result

#from pprint import pprint
dict_diff_deep(source, dest, result)

if args.result_file:
    # Writing result
    result.write()
else:
    f = stringBuf()
    result.write(f)
    print(str(f))
